
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python packages
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
    assignees:
      - "sparsh"
    reviewers:
      - "NoxxOP"
    commit-message:
      prefix: "pip"
      include: "scope"
    
  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "sparsh"
    reviewers:
      - "sparsh"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    
  # Check for docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "sparash"
    reviewers:
      - "sparsh"
    commit-message:
      prefix: "docker"
      include: "scope"

