name: Notify Forks About Update

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify forks via issue
        run: |
          echo "Checking forked repos for update notification..."

          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/sparshshivhare2007-pixel/sparshXshizuka/forks \
            | jq -r '.[].full_name' \
            | while read repo; do
              echo "Creating issue in fork: $repo"
              curl -X POST \
                -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/$repo/issues \
                -d "{\"title\": \"🔄 New Update Available\", \"body\": \"Your fork of [sparshXshizuka](https://github.com/sparshshivhare2007-pixel/sparshXshizuka) is behind. Please merge the latest changes from the upstream repo.\n\nThanks! 🙌\"}"
            done
